/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/search/components/HistoryCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/social/components/MyRecipesCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/social/screens/MyRecipesList`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/social/screens/EditProfileForm`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/search/components/HistoryCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/social/components/MyRecipesCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/social/screens/MyRecipesList`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/social/screens/EditProfileForm`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/modules/search/components/HistoryCard${`?${string}` | `#${string}` | ''}` | `/../src/modules/social/components/MyRecipesCard${`?${string}` | `#${string}` | ''}` | `/../src/modules/social/screens/MyRecipesList${`?${string}` | `#${string}` | ''}` | `/../src/modules/social/screens/EditProfileForm${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/search/components/HistoryCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/social/components/MyRecipesCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/social/screens/MyRecipesList`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/social/screens/EditProfileForm`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
