/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/modules/recipes/components/BottomBar`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/planning/utils/mealPlanSharing`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/planning/components/SharedMealPlan`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/pantry/screens/Pantry`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/shopping/screens/ShoppingList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../src/modules/recipes/components/BottomBar`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/planning/utils/mealPlanSharing`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/planning/components/SharedMealPlan`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/pantry/screens/Pantry`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/shopping/screens/ShoppingList`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../src/modules/recipes/components/BottomBar${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../src/modules/planning/utils/mealPlanSharing${`?${string}` | `#${string}` | ''}` | `/../src/modules/planning/components/SharedMealPlan${`?${string}` | `#${string}` | ''}` | `/../src/modules/pantry/screens/Pantry${`?${string}` | `#${string}` | ''}` | `/../src/modules/shopping/screens/ShoppingList${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/modules/recipes/components/BottomBar`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/planning/utils/mealPlanSharing`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/planning/components/SharedMealPlan`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/pantry/screens/Pantry`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/shopping/screens/ShoppingList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
